### ISSUE TITLE
cannot sync OCI bitnami chart

### ISSUE THREAD

**Issue by poligraph** [bitnami/charts-syncer#182]
I have pretty small config for chart-syncer to sync memcache to my google artifacts registry

```
source:
  repo:
    kind: OCI
    url:  https://registry-1.docker.io/bitnamicharts
target:
  repoName: helm-charts
  repo:
    kind: OCI
    url: https://europe-docker.pkg.dev/XXX-YYY/helm-charts
charts:
  - memcached
  - common
relocateContainerImages: false
```

but when I run `charts-syncer sync`

I have got 
```
charts-syncer sync
I0523 14:35:51.734377   13980 sync.go:49] Looking for the default config charts-syncer.yaml
I0523 14:35:51.736451   13980 oci.go:428] Attempting to retrieve remote index...
INFO[0001] trying next host                              error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
Error: unable to download index: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

I found similar issue here https://github.com/bitnami/charts/issues/16434
Am I doing something wrong? Or missed docs example?

Thanks.

**Comment by nickvth** [comment]
Same issue here, can't sync https://registry-1.docker.io/bitnamicharts 
Is there an index file?

**Comment by wilmardo** [comment]
This is a shortcoming in the current repo, it currently cannot fetch a anonymous access token which is needed in the according to the v2 Docker registry spec to pull and list public images:
https://github.com/orgs/community/discussions/26279#discussioncomment-3251171
https://www.arthurkoziel.com/dockerhub-registry-api/

I have started working on this but at this point I am not sure if it is feasible to keep backwards compatibility but we will see :)

You can see the changes here: 
https://github.com/wilmardo/charts-syncer/tree/fix-182

Hopefully I will found time soon to finish this and a PR in to get the discussion started :)

**Comment by wilmardo** [comment]
Opened #190 to address this, open for feedback!
